### ISSUE TITLE
ncgoher latest release fails to build with Rust > 1.79

### ISSUE THREAD

**Issue by 0323pin** [jansc/ncgopher#388]
Hi,

FYI, see title.
This is because the time crate fails with:
```
error[E0282]: type annotations needed for `Box<_>`
  --> /pbulk/work/devel/cargo-outdated/work/vendor/time-0.3.29/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```
The solution is to update time to 0.3.36 and cut a new release.

**Comment by jansc** [comment]
Thank you for the heads-up and sorry for the late answer. Somehow, GitHub doesn't send me email notifications for new issues. Pushed a new release (0.7.0).

**Comment by 0323pin** [comment]
@jansc no worries. I'll see if I can get the package update done before my work travel, else I'll get it done in a week. Thanks

**Comment by jansc** [comment]
Created a new release that should solve the problem.

**Comment by 0323pin** [comment]
Sorry, fogot to close this. Everything is fine now.
Tack!

**Comment by jansc** [comment]
No stress! Good to hear that everything is ok now :-) And thanks again for the heads-up.
